projects:
  CloudSheetBackendEnv:
    schemaPath: amplify/backend/api/CloudSheetBackendEnv/build/schema.graphql
    includes:
      - src/graphql/mutations.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
